vrep=remApi('remoteApi');
vrep.simxFinish(-1); 
clientID=vrep.simxStart('127.0.0.1',19999,true,true,5000,5);
if (clientID>-1)
    %getHandles
    [returnCode,turtlebot]=vrep.simxGetObjectHandle(clientID,'Turtlebot2',vrep.simx_opmode_blocking);
    [returnCode,origin]=vrep.simxGetObjectHandle(clientID,'Origin',vrep.simx_opmode_blocking);
    [returnCode,maxBound]=vrep.simxGetObjectHandle(clientID,'Border',vrep.simx_opmode_blocking);
    [returnCode,robotPart1]=vrep.simxGetObjectHandle(clientID,'RobotPart1',vrep.simx_opmode_blocking);
    [returnCode,robotPart2]=vrep.simxGetObjectHandle(clientID,'RobotPart2',vrep.simx_opmode_blocking);
    [returnCode,Onep1]=vrep.simxGetObjectHandle(clientID,'Obstacle1Point1',vrep.simx_opmode_blocking);
    [returnCode,Onep2]=vrep.simxGetObjectHandle(clientID,'Obstacle1Point2',vrep.simx_opmode_blocking);
    [returnCode,Onep3]=vrep.simxGetObjectHandle(clientID,'Obstacle1Point3',vrep.simx_opmode_blocking);
    [returnCode,Onep4]=vrep.simxGetObjectHandle(clientID,'Obstacle1Point4',vrep.simx_opmode_blocking);
    [returnCode,Twop1]=vrep.simxGetObjectHandle(clientID,'Obstacle2Point1',vrep.simx_opmode_blocking);
    [returnCode,Twop2]=vrep.simxGetObjectHandle(clientID,'Obstacle2Point2',vrep.simx_opmode_blocking);
    [returnCode,Twop3]=vrep.simxGetObjectHandle(clientID,'Obstacle2Point3',vrep.simx_opmode_blocking);
    [returnCode,Twop4]=vrep.simxGetObjectHandle(clientID,'Obstacle2Point4',vrep.simx_opmode_blocking);
    [returnCode,Threep1]=vrep.simxGetObjectHandle(clientID,'Obstacle3Point1',vrep.simx_opmode_blocking);
    [returnCode,Threep2]=vrep.simxGetObjectHandle(clientID,'Obstacle3Point2',vrep.simx_opmode_blocking);
    [returnCode,Threep3]=vrep.simxGetObjectHandle(clientID,'Obstacle3Point3',vrep.simx_opmode_blocking);
    [returnCode,Threep4]=vrep.simxGetObjectHandle(clientID,'Obstacle3Point4',vrep.simx_opmode_blocking);
    [returnCode,Fourp1]=vrep.simxGetObjectHandle(clientID,'Obstacle4Point1',vrep.simx_opmode_blocking);
    [returnCode,Fourp2]=vrep.simxGetObjectHandle(clientID,'Obstacle4Point2',vrep.simx_opmode_blocking);
    [returnCode,Fourp3]=vrep.simxGetObjectHandle(clientID,'Obstacle4Point3',vrep.simx_opmode_blocking);
    [returnCode,Fourp4]=vrep.simxGetObjectHandle(clientID,'Obstacle4Point4',vrep.simx_opmode_blocking);
    [returnCode,Fivep1]=vrep.simxGetObjectHandle(clientID,'Obstacle5Point1',vrep.simx_opmode_blocking);
    [returnCode,Fivep2]=vrep.simxGetObjectHandle(clientID,'Obstacle5Point2',vrep.simx_opmode_blocking);
    [returnCode,Fivep3]=vrep.simxGetObjectHandle(clientID,'Obstacle5Point3',vrep.simx_opmode_blocking);
    [returnCode,Fivep4]=vrep.simxGetObjectHandle(clientID,'Obstacle5Point4',vrep.simx_opmode_blocking);
    [returnCode,Sixp1]=vrep.simxGetObjectHandle(clientID,'Obstacle6Point1',vrep.simx_opmode_blocking);
    [returnCode,Sixp2]=vrep.simxGetObjectHandle(clientID,'Obstacle6Point2',vrep.simx_opmode_blocking);
    [returnCode,Sixp3]=vrep.simxGetObjectHandle(clientID,'Obstacle6Point3',vrep.simx_opmode_blocking);
    [returnCode,Sixp4]=vrep.simxGetObjectHandle(clientID,'Obstacle6Point4',vrep.simx_opmode_blocking);
    
    %check Location
    test = 1;
    [returnCode,positionOfRobot]=vrep.simxGetObjectPosition(clientID,turtlebot,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfRobotPart1]=vrep.simxGetObjectPosition(clientID,robotPart1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfRobotPart2]=vrep.simxGetObjectPosition(clientID,robotPart2,origin,vrep.simx_opmode_oneshot_wait);
    L = pdist([positionOfRobotPart1;positionOfRobotPart2],'euclidean');
    [returnCode,positionOfOnep1]=vrep.simxGetObjectPosition(clientID,Onep1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfOnep2]=vrep.simxGetObjectPosition(clientID,Onep2,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfOnep3]=vrep.simxGetObjectPosition(clientID,Onep3,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfOnep4]=vrep.simxGetObjectPosition(clientID,Onep4,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfTwop1]=vrep.simxGetObjectPosition(clientID,Twop1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfTwop2]=vrep.simxGetObjectPosition(clientID,Twop2,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfTwop3]=vrep.simxGetObjectPosition(clientID,Twop3,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfTwop4]=vrep.simxGetObjectPosition(clientID,Twop4,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfThreep1]=vrep.simxGetObjectPosition(clientID,Threep1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfThreep2]=vrep.simxGetObjectPosition(clientID,Threep2,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfThreep3]=vrep.simxGetObjectPosition(clientID,Threep3,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfThreep4]=vrep.simxGetObjectPosition(clientID,Threep4,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFourp1]=vrep.simxGetObjectPosition(clientID,Fourp1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFourp2]=vrep.simxGetObjectPosition(clientID,Fourp2,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFourp3]=vrep.simxGetObjectPosition(clientID,Fourp3,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFourp4]=vrep.simxGetObjectPosition(clientID,Fourp4,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFivep1]=vrep.simxGetObjectPosition(clientID,Fivep1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFivep2]=vrep.simxGetObjectPosition(clientID,Fivep2,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFivep3]=vrep.simxGetObjectPosition(clientID,Fivep3,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfFivep4]=vrep.simxGetObjectPosition(clientID,Fivep4,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfSixp1]=vrep.simxGetObjectPosition(clientID,Sixp1,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfSixp2]=vrep.simxGetObjectPosition(clientID,Sixp2,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfSixp3]=vrep.simxGetObjectPosition(clientID,Sixp3,origin,vrep.simx_opmode_oneshot_wait);
    [returnCode,positionOfSixp4]=vrep.simxGetObjectPosition(clientID,Sixp4,origin,vrep.simx_opmode_oneshot_wait);
    
    positionOfOnep1 = round(positionOfOnep1);
    positionOfOnep2 = round(positionOfOnep2);
    positionOfOnep3 = round(positionOfOnep3);
    positionOfOnep4 = round(positionOfOnep4);
    positionOfTwop1 = round(positionOfTwop1);
    positionOfTwop2 = round(positionOfTwop2);
    positionOfTwop3 = round(positionOfTwop3);
    positionOfTwop4 = round(positionOfTwop4);
    positionOfThreep1 = round(positionOfThreep1);
    positionOfThreep2 = round(positionOfThreep2);
    positionOfThreep3 = round(positionOfThreep3);
    positionOfThreep4 = round(positionOfThreep4);
    positionOfFourp1 = round(positionOfFourp1);
    positionOfFourp2 = round(positionOfFourp2);
    positionOfFourp3 = round(positionOfFourp3);
    positionOfFourp4 = round(positionOfFourp4);
    positionOfFivep1 = round(positionOfFivep1);
    positionOfFivep2 = round(positionOfFivep2);
    positionOfFivep3 = round(positionOfFivep3);
    positionOfFivep4 = round(positionOfFivep4);
    positionOfSixp1 = round(positionOfSixp1);
    positionOfSixp2 = round(positionOfSixp2);
    positionOfSixp3 = round(positionOfSixp3);
    positionOfSixp4 = round(positionOfSixp4);
end
 vrep.simxFinish(-1);
 vrep.delete();